# Generated by Django 4.2.5 on 2023-09-10 10:14

import VehiSenseWeb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carbrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=VehiSenseWeb.models.filepath)),
                ('brand', models.TextField(max_length=100)),
            ],
        ),
    ]
