# Generated by Django 4.2.5 on 2023-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0002_carbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
