# Generated by Django 4.2.5 on 2023-09-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0003_carbrand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
