# Generated by Django 4.2.5 on 2023-09-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0004_carbrand_status_alter_carbrand_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
