# Generated by Django 4.2.5 on 2023-09-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0005_alter_carbrand_description_alter_record_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
