# Generated by Django 4.2.5 on 2023-09-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0006_record_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
