# Generated by Django 4.2.5 on 2023-09-11 06:48

import VehiSenseWeb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0008_alter_cartypes_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=VehiSenseWeb.models.vehicle_filepath)),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('enginetype', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('mvfileno', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('engineno', models.CharField(max_length=100)),
                ('chasisno', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
