# Generated by Django 4.2.5 on 2023-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0010_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
