# Generated by Django 4.2.5 on 2023-09-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0011_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
