# Generated by Django 4.2.5 on 2023-09-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0013_alter_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VehiSenseWeb.carbrand'),
        ),
    ]
