# Generated by Django 4.2.5 on 2023-09-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0016_alter_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='brand',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VehiSenseWeb.carbrand', to_field='brand'),
        ),
    ]
