# Generated by Django 4.2.5 on 2023-09-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0017_alter_carbrand_brand_alter_vehicle_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='brand',
            new_name='vbrand',
        ),
    ]
