# Generated by Django 4.2.5 on 2023-09-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0018_rename_brand_vehicle_vbrand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vbrand',
            new_name='brand',
        ),
    ]
